services:
  - type: web
    name: sbux-tips
    env: node
    region: oregon
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: SESSION_SECRET
        generateValue: true
      - key: OCR_ENGINE
        value: auto
      # Add your Azure credentials in Render dashboard under Environment
      # - key: AZURE_CV_KEY
      #   sync: false
      # - key: AZURE_CV_ENDPOINT
      #   sync: false
